import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    // Loading Screen
    'loading.connecting': 'Подключаемся...',
    'loading.wait': 'Секунду...',
    'loading.loadingData': 'Загружаем данные...',
    'loading.appName': 'Saturway',
    'loading.subtitle': 'AI Organizer',

    // Permission Screen
    'permission.title': 'Включить уведомления?',
    'permission.description': 'Мы будем отправлять напоминания о важных задачах в удобное время',
    'permission.benefit1': 'Не пропустите важные задачи',
    'permission.benefit2': 'Умные напоминания в удобное время',
    'permission.benefit3': 'Можно отключить в любой момент',
    'permission.allow': 'Включить уведомления',
    'permission.skip': 'Может быть, позже',

    // Error Screen
    'error.title': 'Что-то пошло не так',
    'error.defaultMessage': 'Не удалось подключиться. Проверьте интернет и попробуйте снова',
    'error.code': 'Код ошибки:',
    'error.retry': 'Попробовать снова',
    'error.support': 'Техподдержка',
    'error.helpTitle': 'Если проблема повторяется, попробуйте:',
    'error.help1': '• Проверить подключение к интернету',
    'error.help2': '• Перезапустить приложение',
    'error.help3': '• Обновить Telegram',

    // Demo Screen
    'demo.title': 'Экраны Авторизации',
    'demo.subtitle': 'Выберите экран для просмотра',
    'demo.loadingScreen': 'Loading Screen',
    'demo.loadingScreenDesc': '(Экран загрузки)',
    'demo.permissionScreen': 'Permission Screen',
    'demo.permissionScreenDesc': '(Запрос разрешений)',
    'demo.errorScreen': 'Error Screen',
    'demo.errorScreenDesc': '(Экран ошибки)',
    'demo.backToMenu': 'Вернуться в меню',
    'demo.features': 'Особенности:',
    'demo.feature1': '✓ Поддержка светлой и темной темы',
    'demo.feature2': '✓ Плавные анимации с Motion',
    'demo.feature3': '✓ Океанская цветовая схема',
    'demo.feature4': '✓ Адаптивный дизайн',
    'demo.feature5': '✓ Профессиональные иконки',
    'demo.feature6': '✓ Анимированные океанские эффекты',
    'demo.feature7': '✓ Пузырьки и подводные лучи',
    'demo.feature8': '✓ Ripple-эффекты на кнопках',
    'demo.version': 'Saturway Auth Screens v2.0 • Ocean Edition',

    // Welcome Screen
    'welcome.title': 'Добро пожаловать в Saturway',
    'welcome.description': 'Ваш AI-помощник для осознанной продуктивности и сбалансированной жизни',
    'welcome.feature1': 'Умная организация задач',
    'welcome.feature2': 'Отслеживание уровня энергии',
    'welcome.feature3': 'Аналитика на основе ИИ',
    'welcome.getStarted': 'Начать',

    // Dashboard
    'dashboard.greeting': 'Привет',
    'dashboard.subtitle': 'Вот обзор вашего дня',
    'dashboard.tasksToday': 'Задачи на сегодня',
    'dashboard.completed': 'Выполнено',
    'dashboard.pending': 'В процессе',
    'dashboard.energyLevel': 'Уровень энергии',
    'dashboard.currentEnergy': 'Текущий уровень',
    'dashboard.aiTip': 'AI Совет дня',
    'dashboard.tipTitle': 'Время для перерыва',
    'dashboard.tipContent': 'Вы работаете уже 2 часа. Короткая прогулка поможет восстановить концентрацию.',
    'dashboard.quickActions': 'Быстрые действия',
    'dashboard.addTask': 'Добавить задачу',
    'dashboard.trackEnergy': 'Отследить энергию',
    'dashboard.viewInsights': 'Посмотреть аналитику',
    'dashboard.recentTasks': 'Недавние задачи',
    'dashboard.viewAll': 'Посмотреть все',

    // Task List
    'tasks.title': 'Мои задачи',
    'tasks.subtitle': 'Управляйте своими задачами эффективно',
    'tasks.addNew': 'Новая задача',
    'tasks.all': 'Все',
    'tasks.active': 'Активные',
    'tasks.completed': 'Завершённые',
    'tasks.important': 'Важные',
    'tasks.filterSort': 'Фильтр и сортировка',
    'tasks.sortByPriority': 'По приоритету',
    'tasks.priority.label': 'Приоритет',
    'tasks.priority.high': 'Высокий',
    'tasks.priority.medium': 'Средний',
    'tasks.priority.low': 'Низкий',
    'tasks.due': 'Срок:',
    'tasks.today': 'Сегодня',
    'tasks.tomorrow': 'Завтра',
    'tasks.thisWeek': 'На этой неделе',
    'tasks.empty': 'Задач пока нет',
    'tasks.emptyDescription': 'Добавьте первую задачу, чтобы начать',
    'tasks.delete': 'Удалить',
    'tasks.edit': 'Редактировать',
    'tasks.markComplete': 'Отметить выполненной',
    'tasks.markIncomplete': 'Отметить невыполненной',

    // Energy Tracker
    'energy.title': 'Трекер энергии',
    'energy.currentLevel': 'Текущий уровень',
    'energy.logEnergy': 'Записать уровень',
    'energy.history': 'История за неделю',
    'energy.patterns': 'Ваши паттерны',
    'energy.peakTime': 'Пик энергии',
    'energy.morning': 'Утро (9-12)',
    'energy.lowTime': 'Спад энергии',
    'energy.afternoon': 'После обеда (14-16)',
    'energy.recommendation': 'Рекомендации',
    'energy.recommendationText': 'Планируйте важные задачи на утро, когда ваша энергия на пике',
    'energy.levels.veryLow': 'Очень низкий',
    'energy.levels.low': 'Низкий',
    'energy.levels.medium': 'Средний',
    'energy.levels.high': 'Высокий',
    'energy.levels.veryHigh': 'Очень высокий',
    'energy.empty': 'Данных пока нет',
    'energy.emptyDescription': 'Начните отслеживать свой уровень энергии',

    // AI Insights
    'insights.title': 'AI Аналитика',
    'insights.productivity': 'Продуктивность',
    'insights.thisWeek': 'На этой неделе',
    'insights.tasksCompleted': 'задач выполнено',
    'insights.comparedToLast': 'по сравнению с прошлой неделей',
    'insights.weeklyProgress': 'Прогресс за неделю',
    'insights.mon': 'Пн',
    'insights.tue': 'Вт',
    'insights.wed': 'Ср',
    'insights.thu': 'Чт',
    'insights.fri': 'Пт',
    'insights.sat': 'Сб',
    'insights.sun': 'Вс',
    'insights.energyCorrelation': 'Корреляция энергии и задач',
    'insights.correlationText': 'Вы завершаете на 40% больше задач, когда ваш уровень энергии выше 70%',
    'insights.bestTime': 'Лучшее время для работы',
    'insights.bestTimeText': 'Ваша продуктивность максимальна между 9:00 и 12:00',
    'insights.suggestions': 'Персональные рекомендации',
    'insights.suggestion1Title': 'Оптимизируйте расписание',
    'insights.suggestion1Text': 'Перенесите сложные задачи на утро',
    'insights.suggestion2Title': 'Делайте перерывы',
    'insights.suggestion2Text': 'Добавьте 10-минутные перерывы каждые 90 минут',
    'insights.suggestion3Title': 'Следите за энергией',
    'insights.suggestion3Text': 'Записывайте уровень энергии чаще для точной аналитики',
    'insights.emptyTitle': 'Недостаточно данных для аналитики',
    'insights.emptyDescription': 'Начните добавлять задачи и отслеживать энергию, чтобы получить персонализированные рекомендации от AI',
    'insights.startTracking': 'Начать отслеживание',

    // Settings
    'settings.title': 'Настройки',
    'settings.profile': 'Профиль',
    'settings.username': 'Имя пользователя',
    'settings.email': 'Email',
    'settings.password': 'Пароль',
    'settings.aboutMe': 'О себе',
    'settings.aboutMePlaceholder': 'Расскажите о себе...',
    'settings.saveProfile': 'Сохранить профиль',
    'settings.language': 'Язык',
    'settings.languageDescription': 'Выберите предпочитаемый язык интерфейса',
    'settings.background': 'Фон приложения',
    'settings.backgroundDescription': 'Выберите стиль океанского фона',
    'settings.bgOceanAccents': 'Океанские акценты',
    'settings.bgCaustics': 'Солнечные лучи',
    'settings.bgWaves': 'Волны',
    'settings.bgDepthLayers': 'Глубины океана',
    'settings.bgMeshGrid': 'Морская сетка',
    'settings.bgMinimal': 'Минимальный',
    'settings.privacy': 'Приватность',
    'settings.notifications': 'Push-уведомления',
    'settings.notificationsDesc': 'Получать напоминания о задачах',
    'settings.dataSharing': 'Передача данных',
    'settings.dataSharingDesc': 'Помогите улучшить приложение анонимными данными',
    'settings.aboutAuthor': 'О приложении',
    'settings.aboutAuthorTitle': 'О приложении',
    'settings.aboutAuthorText1': 'Saturway создан для того, чтобы помочь вам достичь осознанной продуктивности и сбалансированной жизни.',
    'settings.aboutAuthorText2': 'Наша миссия — объединить технологии ИИ с продуманным дизайном для создания инструментов, которые уважают ваше время, энергию и психическое здоровье.',
    'settings.version': 'Версия 1.0.0 • © 2025 Saturway',
    'settings.privacyPolicy': 'Политика конфиденциальности',
    'settings.privacyPolicyTitle': 'Политика конфиденциальности',
    'settings.dataCollection': 'Сбор данных',
    'settings.dataCollectionText': 'Мы собираем только необходимые данные для наилучшего опыта. Это включает ваши задачи, данные отслеживания энергии и настройки.',
    'settings.dataSecurity': 'Безопасность данных',
    'settings.dataSecurityText': 'Ваши данные зашифрованы и надёжно хранятся. Мы никогда не продаём и не передаём вашу личную информацию третьим лицам.',
    'settings.yourRights': 'Ваши права',
    'settings.yourRightsText': 'Вы можете получить доступ, изменить или удалить свои данные в любое время. Свяжитесь с нами для экспорта данных.',
    'settings.termsOfService': 'Условия использования',
    'settings.termsOfServiceTitle': 'Условия использования',
    'settings.acceptanceOfTerms': 'Принятие условий',
    'settings.acceptanceOfTermsText': 'Используя Saturway, вы соглашаетесь с этими условиями. Если вы не согласны, пожалуйста, не используйте приложение.',
    'settings.license': 'Лицензия',
    'settings.licenseText': 'Мы предоставляем вам ограниченную, неисключительную, непередаваемую лицензию на использование Saturway для личной продуктивности.',
    'settings.prohibitedUses': 'Запрещённое использование',
    'settings.prohibitedUsesText': 'Вы не можете использовать приложение для незаконной деятельности, причинения вреда другим или нарушения применимых законов.',
    'settings.changesToTerms': 'Изменения условий',
    'settings.changesToTermsText': 'Мы оставляем за собой право изменять эти условия в любое время. Продолжение использования означает принятие обновлённых условий.',
    'settings.copyright': 'Авторские права и лицензии',
    'settings.copyrightTitle': 'Авторские права и лицензии',
    'settings.copyrightText1': '© 2025 Saturway. Все права защищены.',
    'settings.copyrightText2': 'Название Saturway, логотип и дизайн являются товарными знаками Saturway. Несанкционированное использование запрещено.',
    'settings.openSourceLibraries': 'Библиотеки с открытым кодом',
    'settings.openSourceLibrariesText': 'Это приложение использует библиотеки с открытым кодом, лицензированные под MIT, Apache 2.0 и другими разрешающими лицензиями. Полную информацию можно найти в репозитории приложения.',
    'settings.appVersion': 'Saturway v1.0.0',
    'settings.appTagline': 'Создано с ❤️ для осознанной продуктивности',

    // Bottom Navigation
    'nav.dashboard': 'Главная',
    'nav.tasks': 'Задачи',
    'nav.energy': 'Энергия',
    'nav.insights': 'Аналитика',
    'nav.settings': 'Настройки',
    'nav.today': 'Сегодня',
    'nav.profile': 'Профиль',

    // Onboarding
    'onboarding.skip': 'Пропустить',
    'onboarding.step1.title': 'На чём твой главный фокус?',
    'onboarding.step1.subtitle': 'Выбери основное направление',
    'onboarding.step1.work': 'Работа / Проекты',
    'onboarding.step1.health': 'Здоровье / Спорт',
    'onboarding.step1.personal': 'Личное развитие',
    'onboarding.step1.mix': 'Микс',
    'onboarding.step2.title': 'Какой у тебя обычно график?',
    'onboarding.step2.subtitle': 'Это поможет настроить напоминания',
    'onboarding.step2.stable': 'Стабильный',
    'onboarding.step2.stableDesc': 'Офис / 9–18',
    'onboarding.step2.flexible': 'Гибкий',
    'onboarding.step2.flexibleDesc': 'Могу работать в разное время',
    'onboarding.step2.freelance': 'Фриланс / Хаос',
    'onboarding.step2.freelanceDesc': 'Каждый день по-разному',
    'onboarding.step3.title': 'Во сколько ты обычно начинаешь день?',
    'onboarding.step3.subtitle': 'Мы будем присылать утренний план',
    'onboarding.step3.early': 'Ранняя пташка',
    'onboarding.step3.morning': 'Стандарт',
    'onboarding.step3.mid': 'Чуть позже',
    'onboarding.step3.late': 'После полудня',
    'onboarding.step4.title': 'Как чувствуешь себя по энергии сейчас?',
    'onboarding.step4.subtitle': 'Первая точка для отслеживания',
    'onboarding.step4.tired': 'Устал',
    'onboarding.step4.low': 'Низко',
    'onboarding.step4.okay': 'Нормально',
    'onboarding.step4.good': 'Хорошо',
    'onboarding.step4.great': 'Отлично',

    // Today Screen
    'today.goodMorning': 'Доброе утро',
    'today.goodAfternoon': 'Добрый день',
    'today.goodEvening': 'Добрый вечер',
    'today.subtitle': 'Начни день правильно',
    'today.tasksToday': 'Задачи на сегодня',
    'today.noTasks': 'Задач пока нет',
    'today.of': 'из',
    'today.completed': 'выполнено',
    'today.addTaskPlaceholder': 'Например: Подготовить презентацию для клиента',
    'today.energyNow': 'Твоя энергия сейчас',
    'today.currentEnergy': 'Сейчас',
    'today.avgEnergy': 'Средняя',
    'today.trackEnergyPrompt': 'Отметь своё состояние, чтобы я подстроил советы',
    'today.energy.tired': 'Устал',
    'today.energy.low': 'Низко',
    'today.energy.okay': 'Нормально',
    'today.energy.good': 'Хорошо',
    'today.energy.great': 'Отлично',
    'today.aiTip': 'AI Совет дня',
    'today.tipTitle': 'Начни с одной самой важной задачи',
    'today.tipContent': 'Остальное подстроим по ходу дня',
    'today.nearestTasks': 'Ближайшие задачи',
    'today.noTasksTitle': 'Задачи на сегодня ещё не созданы',
    'today.noTasksDesc': 'Добавь первую задачу чтобы начать',
    'today.createFirstTask': 'Создать первую задачу',

    // Review Screen
    'review.title': 'Как прошёл день?',
    'review.subtitle': '3 коротких вопроса, займет 1–2 минуты',
    'review.goodLabel': 'Что сегодня получилось?',
    'review.goodPlaceholder': 'Например: Закончил презентацию, пошёл на тренировку',
    'review.badLabel': 'Что не успел(а) или отложил(а)?',
    'review.badPlaceholder': 'Например: Не ответил на письма',
    'review.endEnergyLabel': 'Как чувствуешь себя по энергии в конце дня?',
    'review.submit': 'Завершить день',
    'review.aiSummaryTitle': 'Итоги дня',
    'review.aiAdviceTitle': 'Совет на завтра',
    'review.loadError': 'Не удалось загрузить обзор',
    'review.saveError': 'Не удалось сохранить обзор',
    'review.question1': 'Что сегодня получилось?',
    'review.question1Placeholder': 'Например: Закончил презентацию, пошёл на тренировку',
    'review.question2': 'Что не успел(а) или отложил(а)?',
    'review.question2Placeholder': 'Например: Не ответил на письма',
    'review.question3': 'Как чувствуешь себя по энергии в конце дня?',
    'review.completeDay': 'Завершить день',
    'review.complete': 'Отличная работа!',
    'review.completeSubtitle': 'День завершён',
    'review.daySummary': 'Итоги дня',
    'review.summaryPoint1': 'Выполнено 8 из 10 задач — отличный результат',
    'review.summaryPoint2': 'Энергия была стабильной в течение дня',
    'review.summaryPoint3': 'Продуктивность выше на 15% по сравнению со вчера',
    'review.tomorrowTips': 'Совет на завтра',
    'review.tip1': 'Начни с самой сложной задачи утром',
    'review.tip2': 'Запланируй короткие перерывы каждые 90 минут',
    'review.planTomorrow': 'План на завтра',

    // Profile Screen
    'profile.member': 'Участник с 2025',
    'profile.editName': 'Редактировать имя',
    'profile.editNamePlaceholder': 'Введите ваше имя',
    'profile.save': 'Сохранить',
    'profile.language': 'Язык приложения',
    'profile.languageDesc': 'Выбери предпочитаемый язык',
    'profile.reminders': 'Напоминания',
    'profile.morningPlan': 'Утренний план',
    'profile.morningPlanTime': 'в 9:00 по твоему времени',
    'profile.eveningReview': 'Вечерний обзор',
    'profile.eveningReviewTime': 'в 20:30',
    'profile.about': 'О приложении',
    'profile.version': 'Версия 0.1 MVP',
    'profile.tagline': 'Создано с ❤️ для продуктивности',
    'profile.logout': 'Выйти и очистить кэш',
    'profile.deleteData': 'Удалить мои данные',
    'profile.deleteConfirmTitle': 'Удалить все данные?',
    'profile.deleteConfirmDesc': 'Это действие необратимо. Все твои задачи, данные по энергии и настройки будут удалены.',
    'profile.cancel': 'Отмена',
    'profile.deleteConfirm': 'Удалить',

    // Habit Challenge
    'habit.title': '40-дневный челлендж',
    'habit.subtitle': 'Выбери маленькую привычку, которую хочешь закрепить',
    'habit.focusSession': '1 фокус-сессия в день',
    'habit.trackEnergy': 'Отмечать энергию каждый день',
    'habit.oneTask': '1 важная задача в день',
    'habit.custom': 'Своя привычка',
    'habit.customPlaceholder': 'Например: Читать 10 минут',
    'habit.create': 'Создать',
    'habit.cancel': 'Отмена',
    'habit.presets.focus': '1 фокус-сессия в день',
    'habit.presets.workout': '5 минут зарядки',
    'habit.presets.journal': '3 предложения в дневнике',
    'habit.dayProgress': 'День {{current}} из {{target}}',
    'habit.markToday': 'Отметить на сегодня выполнено',
    'habit.todayDone': 'Сегодня уже отмечено',
    'habit.empty': 'Пока нет активного челленджа',
    'habit.days': 'дней',
    'habit.details': 'Подробнее',
    'habit.progressGrid': 'Твой прогресс по дням',
    'habit.chooseToStart': 'Выбери привычку, чтобы начать челлендж',
    'habit.startChallenge': 'Начать челлендж 40 дней',
    'habit.habitTitle': 'Привычка',
    'habit.day': 'День',
    'habit.of': 'из',
    'habit.progress': 'Прогресс',
    'habit.streak': 'Серия',
    'habit.daysInRow': 'дня подряд',
    'habit.motivation': 'Сделай сегодня маленький шаг — отметь выполнение',
    'habit.markDone': 'Отметить сегодня выполнено',
    'habit.completed': 'Привычка закреплена',
    'habit.completedSubtitle': 'Ты держался(ась) 40 дней — это уже устойчивый паттерн',
    'habit.completedDescription': 'Продолжай в своём ритме или выбери новый челлендж',
    'habit.newChallenge': 'Выбрать новую привычку',
    'habit.continueWithout': 'Продолжить без счётчика',
    'habit.detailTitle': 'Привычка за 40 дней',
    'habit.today': 'Сегодня',
    'habit.missed': 'Пропуски',
    'habit.done': 'Выполнено',
    'habit.skipped': 'Пропущено',
    'habit.rate': 'Процент',
    'habit.motivationMissed': 'Ты пропустил(а) {count} дня — это нормально. Главное — вернуться сегодня.',
    'habit.motivationGreat': 'Отличный темп! Продолжай в том же духе 💪',

    // Streak Badge
    'streak.start': 'Start a streak: mark tasks today 👇',
    'streak.days': 'days in a row',
  },
  en: {
    // Loading Screen
    'loading.connecting': 'Connecting...',
    'loading.wait': 'One moment...',
    'loading.loadingData': 'Loading data...',
    'loading.appName': 'Saturway',
    'loading.subtitle': 'AI Organizer',

    // Permission Screen
    'permission.title': 'Enable notifications?',
    'permission.description': 'We will send reminders about important tasks at convenient times',
    'permission.benefit1': "Don't miss important tasks",
    'permission.benefit2': 'Smart reminders at convenient times',
    'permission.benefit3': 'Can be disabled at any time',
    'permission.allow': 'Enable notifications',
    'permission.skip': 'Maybe later',

    // Error Screen
    'error.title': 'Something went wrong',
    'error.defaultMessage': 'Connection failed. Check your internet and try again',
    'error.code': 'Error code:',
    'error.retry': 'Try again',
    'error.support': 'Support',
    'error.helpTitle': 'If the problem persists, try:',
    'error.help1': '• Check internet connection',
    'error.help2': '• Restart the application',
    'error.help3': '• Update Telegram',

    // Demo Screen
    'demo.title': 'Auth Screens',
    'demo.subtitle': 'Choose a screen to preview',
    'demo.loadingScreen': 'Loading Screen',
    'demo.loadingScreenDesc': '(Initial loading)',
    'demo.permissionScreen': 'Permission Screen',
    'demo.permissionScreenDesc': '(Request permissions)',
    'demo.errorScreen': 'Error Screen',
    'demo.errorScreenDesc': '(Error handling)',
    'demo.backToMenu': 'Back to menu',
    'demo.features': 'Features:',
    'demo.feature1': '✓ Light and dark theme support',
    'demo.feature2': '✓ Smooth animations with Motion',
    'demo.feature3': '✓ Ocean color scheme',
    'demo.feature4': '✓ Responsive design',
    'demo.feature5': '✓ Professional icons',
    'demo.feature6': '✓ Animated ocean effects',
    'demo.feature7': '✓ Bubbles and underwater rays',
    'demo.feature8': '✓ Ripple effects on buttons',
    'demo.version': 'Saturway Auth Screens v2.0 • Ocean Edition',

    // Welcome Screen
    'welcome.title': 'Welcome to Saturway',
    'welcome.description': 'Your AI-powered companion for mindful productivity and balanced living',
    'welcome.feature1': 'Smart task organization',
    'welcome.feature2': 'Energy level tracking',
    'welcome.feature3': 'AI-powered insights',
    'welcome.getStarted': 'Get Started',

    // Dashboard
    'dashboard.greeting': 'Hello',
    'dashboard.subtitle': "Here's an overview of your day",
    'dashboard.tasksToday': 'Tasks Today',
    'dashboard.completed': 'Completed',
    'dashboard.pending': 'Pending',
    'dashboard.energyLevel': 'Energy Level',
    'dashboard.currentEnergy': 'Current Level',
    'dashboard.aiTip': 'AI Tip of the Day',
    'dashboard.tipTitle': 'Time for a Break',
    'dashboard.tipContent': "You've been working for 2 hours. A short walk will help restore your focus.",
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.addTask': 'Add Task',
    'dashboard.trackEnergy': 'Track Energy',
    'dashboard.viewInsights': 'View Insights',
    'dashboard.recentTasks': 'Recent Tasks',
    'dashboard.viewAll': 'View All',

    // Task List
    'tasks.title': 'My Tasks',
    'tasks.subtitle': 'Manage your tasks efficiently',
    'tasks.addNew': 'New Task',
    'tasks.all': 'All',
    'tasks.active': 'Active',
    'tasks.completed': 'Completed',
    'tasks.important': 'Important',
    'tasks.filterSort': 'Filter & Sort',
    'tasks.sortByPriority': 'By Priority',
    'tasks.priority.label': 'Priority',
    'tasks.priority.high': 'High',
    'tasks.priority.medium': 'Medium',
    'tasks.priority.low': 'Low',
    'tasks.due': 'Due:',
    'tasks.today': 'Today',
    'tasks.tomorrow': 'Tomorrow',
    'tasks.thisWeek': 'This week',
    'tasks.empty': 'No tasks yet',
    'tasks.emptyDescription': 'Add your first task to get started',
    'tasks.delete': 'Delete',
    'tasks.edit': 'Edit',
    'tasks.markComplete': 'Mark as complete',
    'tasks.markIncomplete': 'Mark as incomplete',

    // Energy Tracker
    'energy.title': 'Energy Tracker',
    'energy.currentLevel': 'Current Level',
    'energy.logEnergy': 'Log Energy',
    'energy.history': 'Weekly History',
    'energy.patterns': 'Your Patterns',
    'energy.peakTime': 'Peak Energy',
    'energy.morning': 'Morning (9-12)',
    'energy.lowTime': 'Energy Dip',
    'energy.afternoon': 'Afternoon (14-16)',
    'energy.recommendation': 'Recommendation',
    'energy.recommendationText': 'Schedule important tasks in the morning when your energy peaks',
    'energy.levels.veryLow': 'Very Low',
    'energy.levels.low': 'Low',
    'energy.levels.medium': 'Medium',
    'energy.levels.high': 'High',
    'energy.levels.veryHigh': 'Very High',
    'energy.empty': 'No data yet',
    'energy.emptyDescription': 'Start tracking your energy levels',

    // AI Insights
    'insights.title': 'AI Insights',
    'insights.productivity': 'Productivity',
    'insights.thisWeek': 'This Week',
    'insights.tasksCompleted': 'tasks completed',
    'insights.comparedToLast': 'compared to last week',
    'insights.weeklyProgress': 'Weekly Progress',
    'insights.mon': 'Mon',
    'insights.tue': 'Tue',
    'insights.wed': 'Wed',
    'insights.thu': 'Thu',
    'insights.fri': 'Fri',
    'insights.sat': 'Sat',
    'insights.sun': 'Sun',
    'insights.energyCorrelation': 'Energy & Task Correlation',
    'insights.correlationText': 'You complete 40% more tasks when your energy level is above 70%',
    'insights.bestTime': 'Best Time to Work',
    'insights.bestTimeText': 'Your productivity peaks between 9:00 AM and 12:00 PM',
    'insights.suggestions': 'Personalized Suggestions',
    'insights.suggestion1Title': 'Optimize Your Schedule',
    'insights.suggestion1Text': 'Move difficult tasks to morning hours',
    'insights.suggestion2Title': 'Take Regular Breaks',
    'insights.suggestion2Text': 'Add 10-minute breaks every 90 minutes',
    'insights.suggestion3Title': 'Track Energy More',
    'insights.suggestion3Text': 'Log your energy levels more frequently for better insights',
    'insights.emptyTitle': 'Not enough data for insights',
    'insights.emptyDescription': 'Start adding tasks and tracking energy to get personalized AI recommendations',
    'insights.startTracking': 'Start Tracking',

    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.username': 'Username',
    'settings.email': 'Email',
    'settings.password': 'Password',
    'settings.aboutMe': 'About Me',
    'settings.aboutMePlaceholder': 'Tell us about yourself...',
    'settings.saveProfile': 'Save Profile',
    'settings.language': 'Language',
    'settings.languageDescription': 'Choose your preferred language for the app interface',
    'settings.background': 'App Background',
    'settings.backgroundDescription': 'Select an oceanic background style',
    'settings.bgOceanAccents': 'Ocean Accents',
    'settings.bgCaustics': 'Sunbeams',
    'settings.bgWaves': 'Waves',
    'settings.bgDepthLayers': 'Ocean Depths',
    'settings.bgMeshGrid': 'Sea Grid',
    'settings.bgMinimal': 'Minimal',
    'settings.privacy': 'Privacy',
    'settings.notifications': 'Push Notifications',
    'settings.notificationsDesc': 'Receive updates about your tasks',
    'settings.dataSharing': 'Data Sharing',
    'settings.dataSharingDesc': 'Help improve the app with anonymous data',
    'settings.aboutAuthor': 'About Author',
    'settings.aboutAuthorTitle': 'About the Author',
    'settings.aboutAuthorText1': 'Saturway is crafted with dedication to help you achieve mindful productivity and balanced living.',
    'settings.aboutAuthorText2': 'Our mission is to combine AI technology with thoughtful design to create tools that respect your time, energy, and mental well-being.',
    'settings.version': 'Version 1.0.0 • © 2025 Saturway',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.privacyPolicyTitle': 'Privacy Policy',
    'settings.dataCollection': 'Data Collection',
    'settings.dataCollectionText': 'We collect only the data necessary to provide you with the best experience. This includes your tasks, energy tracking data, and usage preferences.',
    'settings.dataSecurity': 'Data Security',
    'settings.dataSecurityText': 'Your data is encrypted and stored securely. We never sell or share your personal information with third parties.',
    'settings.yourRights': 'Your Rights',
    'settings.yourRightsText': 'You have the right to access, modify, or delete your data at any time. Contact us for data export requests.',
    'settings.termsOfService': 'Terms of Service',
    'settings.termsOfServiceTitle': 'Terms of Service',
    'settings.acceptanceOfTerms': 'Acceptance of Terms',
    'settings.acceptanceOfTermsText': 'By using Saturway, you agree to these terms. If you do not agree, please do not use the app.',
    'settings.license': 'License',
    'settings.licenseText': 'We grant you a limited, non-exclusive, non-transferable license to use Saturway for personal productivity purposes.',
    'settings.prohibitedUses': 'Prohibited Uses',
    'settings.prohibitedUsesText': 'You may not use the app for illegal activities, to harm others, or to violate any applicable laws.',
    'settings.changesToTerms': 'Changes to Terms',
    'settings.changesToTermsText': 'We reserve the right to modify these terms at any time. Continued use constitutes acceptance of updated terms.',
    'settings.copyright': 'Copyright & Licenses',
    'settings.copyrightTitle': 'Copyright & Licenses',
    'settings.copyrightText1': '© 2025 Saturway. All rights reserved.',
    'settings.copyrightText2': 'The Saturway name, logo, and design are trademarks of Saturway. Unauthorized use is prohibited.',
    'settings.openSourceLibraries': 'Open Source Libraries',
    'settings.openSourceLibrariesText': 'This app uses open-source libraries licensed under MIT, Apache 2.0, and other permissive licenses. Full attribution can be found in the app repository.',
    'settings.appVersion': 'Saturway v1.0.0',
    'settings.appTagline': 'Built with ❤️ for mindful productivity',

    // Bottom Navigation
    'nav.dashboard': 'Dashboard',
    'nav.tasks': 'Tasks',
    'nav.energy': 'Energy',
    'nav.insights': 'Insights',
    'nav.settings': 'Settings',
    'nav.today': 'Today',
    'nav.profile': 'Profile',

    // Onboarding
    'onboarding.skip': 'Skip',
    'onboarding.step1.title': 'What is your main focus?',
    'onboarding.step1.subtitle': 'Choose your primary direction',
    'onboarding.step1.work': 'Work / Projects',
    'onboarding.step1.health': 'Health / Sports',
    'onboarding.step1.personal': 'Personal Development',
    'onboarding.step1.mix': 'Mix',
    'onboarding.step2.title': 'What is your usual schedule?',
    'onboarding.step2.subtitle': 'This will help set up reminders',
    'onboarding.step2.stable': 'Stable',
    'onboarding.step2.stableDesc': 'Office / 9–18',
    'onboarding.step2.flexible': 'Flexible',
    'onboarding.step2.flexibleDesc': 'Can work at different times',
    'onboarding.step2.freelance': 'Freelance / Chaos',
    'onboarding.step2.freelanceDesc': 'Different every day',
    'onboarding.step3.title': 'What time do you usually start your day?',
    'onboarding.step3.subtitle': 'We will send you a morning plan',
    'onboarding.step3.early': 'Early bird',
    'onboarding.step3.morning': 'Standard',
    'onboarding.step3.mid': 'A bit later',
    'onboarding.step3.late': 'Afternoon',
    'onboarding.step4.title': 'How do you feel about energy right now?',
    'onboarding.step4.subtitle': 'First point for tracking',
    'onboarding.step4.tired': 'Tired',
    'onboarding.step4.low': 'Low',
    'onboarding.step4.okay': 'Okay',
    'onboarding.step4.good': 'Good',
    'onboarding.step4.great': 'Great',

    // Today Screen
    'today.goodMorning': 'Good morning',
    'today.goodAfternoon': 'Good afternoon',
    'today.goodEvening': 'Good evening',
    'today.subtitle': 'Start your day right',
    'today.tasksToday': 'Tasks Today',
    'today.noTasks': 'No tasks yet',
    'today.of': 'of',
    'today.completed': 'completed',
    'today.addTaskPlaceholder': 'Example: Prepare a presentation for a client',
    'today.energyNow': 'Your energy level now',
    'today.currentEnergy': 'Current',
    'today.avgEnergy': 'Average',
    'today.trackEnergyPrompt': 'Mark your state to adjust tips',
    'today.energy.tired': 'Tired',
    'today.energy.low': 'Low',
    'today.energy.okay': 'Okay',
    'today.energy.good': 'Good',
    'today.energy.great': 'Great',
    'today.aiTip': 'AI Tip of the Day',
    'today.tipTitle': 'Start with the most important task',
    'today.tipContent': 'We will adjust the rest of the day',
    'today.nearestTasks': 'Nearest tasks',
    'today.noTasksTitle': 'No tasks created for today',
    'today.noTasksDesc': 'Add your first task to start',
    'today.createFirstTask': 'Create first task',

    // Review Screen
    'review.title': 'How was your day?',
    'review.subtitle': '3 short questions, takes 1–2 minutes',
    'review.goodLabel': 'What did you accomplish today?',
    'review.goodPlaceholder': 'Example: Finished a presentation, went to a workout',
    'review.badLabel': 'What did you not get to or postpone?',
    'review.badPlaceholder': 'Example: Did not reply to emails',
    'review.endEnergyLabel': 'How do you feel about energy at the end of the day?',
    'review.submit': 'Complete the day',
    'review.aiSummaryTitle': 'Day summary',
    'review.aiAdviceTitle': 'Tip for tomorrow',
    'review.loadError': 'Failed to load review',
    'review.saveError': 'Failed to save review',
    'review.question1': 'What did you accomplish today?',
    'review.question1Placeholder': 'Example: Finished a presentation, went to a workout',
    'review.question2': 'What did you not get to or postpone?',
    'review.question2Placeholder': 'Example: Did not reply to emails',
    'review.question3': 'How do you feel about energy at the end of the day?',
    'review.completeDay': 'Complete the day',
    'review.complete': 'Great job!',
    'review.completeSubtitle': 'Day completed',
    'review.daySummary': 'Day summary',
    'review.summaryPoint1': 'Completed 8 out of 10 tasks — great result',
    'review.summaryPoint2': 'Energy was stable throughout the day',
    'review.summaryPoint3': 'Productivity is 15% higher than yesterday',
    'review.tomorrowTips': 'Tip for tomorrow',
    'review.tip1': 'Start with the most difficult task in the morning',
    'review.tip2': 'Plan short breaks every 90 minutes',
    'review.planTomorrow': 'Plan for tomorrow',

    // Profile Screen
    'profile.member': 'Member since 2025',
    'profile.editName': 'Edit name',
    'profile.editNamePlaceholder': 'Enter your name',
    'profile.save': 'Save',
    'profile.language': 'App Language',
    'profile.languageDesc': 'Choose your preferred language',
    'profile.reminders': 'Reminders',
    'profile.morningPlan': 'Morning Plan',
    'profile.morningPlanTime': 'at 9:00 in your time zone',
    'profile.eveningReview': 'Evening Review',
    'profile.eveningReviewTime': 'at 20:30',
    'profile.about': 'About the App',
    'profile.version': 'Version 0.1 MVP',
    'profile.tagline': 'Built with ❤️ for productivity',
    'profile.logout': 'Logout and clear cache',
    'profile.deleteData': 'Delete my data',
    'profile.deleteConfirmTitle': 'Delete all data?',
    'profile.deleteConfirmDesc': 'This action is irreversible. All your tasks, energy data, and settings will be deleted.',
    'profile.cancel': 'Cancel',
    'profile.deleteConfirm': 'Delete',

    // Habit Challenge
    'habit.title': '40-day Challenge',
    'habit.subtitle': 'Choose a small habit you want to build',
    'habit.focusSession': '1 focus session per day',
    'habit.trackEnergy': 'Track energy every day',
    'habit.oneTask': '1 important task per day',
    'habit.custom': 'Custom habit',
    'habit.customPlaceholder': 'E.g.: Read for 10 minutes',
    'habit.create': 'Create',
    'habit.cancel': 'Cancel',
    'habit.presets.focus': '1 focus session per day',
    'habit.presets.workout': '5-minute workout',
    'habit.presets.journal': '3 sentences in journal',
    'habit.dayProgress': 'Day {{current}} of {{target}}',
    'habit.markToday': 'Mark today as done',
    'habit.todayDone': 'Already done today',
    'habit.empty': 'No active challenge yet',
    'habit.days': 'days',
    'habit.details': 'Details',
    'habit.progressGrid': 'Your daily progress',
    'habit.chooseToStart': 'Choose a habit to start the challenge',
    'habit.startChallenge': 'Start 40-day challenge',
    'habit.habitTitle': 'Habit',
    'habit.day': 'Day',
    'habit.of': 'of',
    'habit.progress': 'Progress',
    'habit.streak': 'Streak',
    'habit.daysInRow': 'days in a row',
    'habit.motivation': 'Take a small step today — mark it done',
    'habit.markDone': 'Mark today as done',
    'habit.completed': 'Habit built',
    'habit.completedSubtitle': 'You maintained it for 40 days — that\'s a sustainable pattern',
    'habit.completedDescription': 'Continue at your own pace or choose a new challenge',
    'habit.newChallenge': 'Choose a new habit',
    'habit.continueWithout': 'Continue without counter',
    'habit.detailTitle': '40-day Habit',
    'habit.today': 'Today',
    'habit.missed': 'Missed',
    'habit.done': 'Done',
    'habit.skipped': 'Skipped',
    'habit.rate': 'Percentage',
    'habit.motivationMissed': 'You missed {count} days — that\'s okay. The key is to get back on track today.',
    'habit.motivationGreat': 'Great pace! Keep it up 💪',

    // Streak Badge
    'streak.start': 'Start a streak: mark tasks today 👇',
    'streak.days': 'days in a row',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ru] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}